// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars = {
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    'hello',
    { type: 'category', label: 'Tutorial', items: ['tutorial-basics/create-a-document'],},
    { type: 'category', label: 'TCP-IP', items: ['tcp-ip/index'],},
    { type: 'category', label: 'Shell scripting', items: ['shell-scripting/index','shell-scripting/shell-functions'],},
  ],
};

export default sidebars;
