// Sidebars por defecto
/*
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
*/
//END Sidebars por defecto

// Orden de los subgrupos (categorias) en la barra lateral
/*
module.exports = {
  docs: [
    {
      type: 'category',
      label: 'TCP/IP',
      items: ['tcp-ip/index', 'tcp-ip/otros-contenidos'],
    },
    {
      type: 'category',
      label: 'Shell Scripting',
      items: ['shell-scripting/index', 'shell-scripting/shell-functions'],
    },
    {
      type: 'category',
      label: 'Personalizando Docusaurus',
      items: ['sidebar-custom'], // Este es el orden que buscas
    },
  ],
};
*/
//END: Orden de los subgrupos (categorias) en la barra lateral

// Orden con nuevas paginas independientes agregadas y orden personalizado
module.exports = {
  docs: [
    {
      type: 'category',
      label: 'TCP/IP',
      items: ['tcp-ip/index'],  // Asegúrate de que estos archivos existan
    },
    {
      type: 'category',
      label: 'Shell Scripting',
      items: ['shell-scripting/index', 'shell-scripting/shell-functions'], // Asegúrate de que estos archivos existan
    },
    {
      type: 'category',
      label: 'Otras Páginas',
      items: ['docusaurus-sidebar-custom'], // Aquí también debes asegurarte de que los archivos existan
    },
  ],
};


//END: Orden con nuevas paginas independientes agregadas y orden personalizado  

